# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja_operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=10)),
                ('cel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('porcentaje_descuento', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Estados')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('iva', models.IntegerField(choices=[(8, b'8%'), (16, b'16%'), (0, b'0%')])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('existencia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dpto', models.ManyToManyField(to='punto_de_venta.Departamento')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Marca')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Medidas')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('no_ext', models.CharField(max_length=10)),
                ('no_int', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Estados')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('forma_pago', models.CharField(choices=[(b'ef', b'efectivo'), (b'cr', b'credito'), (b'cp', b'cupon')], max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cambio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('iva_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Clientes')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='proveedores',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Ubicacion'),
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedores',
            field=models.ManyToManyField(to='punto_de_venta.Proveedores'),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Productos'),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Ventas'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Contacto'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Ubicacion'),
        ),
    ]
