# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
