# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0002_auto_20190828_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='medidas',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
