# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0003_auto_20190828_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='no_int',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
