# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0004_auto_20190828_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='existencia',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
