# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-30 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0005_auto_20190828_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='porcentaje_descuento',
            field=models.IntegerField(default=0),
        ),
    ]
