# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0006_auto_20190830_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='no_int',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
