# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-11 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import punto_de_venta.validators


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0007_auto_20190905_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja_operacion',
            name='caja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.Cajas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja_operacion',
            name='fecha_cierre',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[punto_de_venta.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[punto_de_venta.validators.validate_porcentaje]),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[punto_de_venta.validators.validate_porcentaje]),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='porcentaje_descuento',
            field=models.IntegerField(default=0, validators=[punto_de_venta.validators.validate_porcentaje]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='existencia',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[punto_de_venta.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[punto_de_venta.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cambio',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[punto_de_venta.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='forma_pago',
            field=models.CharField(choices=[(b'e', b'efectivo'), (b'r', b'credito'), (b'c', b'cupon')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='iva_total',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[punto_de_venta.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[punto_de_venta.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[punto_de_venta.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[punto_de_venta.validators.validate_positive]),
        ),
    ]
