# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0009_auto_20190911_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='codigo_postal',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
