# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
